[package]
name = "irspt-contracts"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
strum = { version = "0.24", features = ["derive"] }
strum_macros = "0.24"
async-trait = "0.1"
