[package]
name = "irspt-core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
irspt-contracts = { path = "../irspt-contracts/" }
irspt-infra = { path = "../irspt-infra/" }
