[package]
name = "irspt-cli"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
issue-invoice = []

default = [
  "issue-invoice"
]

[dependencies]
irspt-contracts = { path = "../irspt-contracts/" }
irspt-infra = { path = "../irspt-infra/" }
irspt-api = { path = "../irspt-api/" }
anyhow = "1.0"
tokio = "1.20.1"
chrono = "0.4"
inquire = { version = "0.2.1", features = ["date"] }
