[package]
name = "irspt-api"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
irspt-contracts = { path = "../irspt-contracts/" }
anyhow = "1.0"
async-trait = "0.1"
thirtyfour = "0.30"
